# Module 3 - NER

In [22]:
import os
os.getcwd()

'C:\\Users\\nirup\\Downloads\\pipeline'

In [23]:
os.chdir('C:\\Users\\nirup\\Downloads\\pipeline')

In [24]:
import pandas as pd
import spacy
from tqdm import tqdm
from spacy.tokens import DocBin
import random
import numpy as np
import csv
from pre_processing import func
from model import func2

In [58]:
df=func2(func('https://www.myrecipes.com/recipe/blueberry-cheesecake'))

In [59]:
df

,Sentence,newline_after,newline_before,nwords,numbers,nnumbers,nnouns,nverbs,nunits,label
0,skip to content,2,0,3,0,0,1,1,0,0
9,holidays and occasions,1,1,3,0,0,2,0,0,0
10,quick and easy,1,1,3,0,0,1,0,0,0
12,bbq and grilling,1,1,3,0,0,2,0,0,0
22,recipe box this link opens in a new tab,1,1,9,0,0,4,1,0,0
...,...,...,...,...,...,...,...,...,...,...
462,subscribe to our newsletter,2,2,4,0,0,2,0,0,0
465,meredith corporation myrecipes is a registered...,1,1,9,0,0,4,1,0,0
466,corporation all rights reserved myrecipes may ...,1,1,10,0,0,4,2,0,0
471,link opens in a new tab,2,1,6,0,0,2,1,0,0
476,close this dialog window,2,2,4,0,0,2,0,0,0

In [60]:
data = df.loc[df['label'] ==1 ]
data

,Sentence,newline_after,newline_before,nwords,numbers,nnumbers,nnouns,nverbs,nunits,label
228,cup graham cracker crumbs about 5 cookie sheets,1,1,8,1,1,5,1,1,1
229,cup reduced fat vanilla wafer crumbs about 20 ...,1,1,9,1,2,4,2,1,1
230,3 tablespoons sugar,1,1,3,1,1,2,0,1,1
231,3 tablespoons butter melted,1,1,4,1,1,1,1,1,1
233,2 cups fresh or frozen wild blueberries thawed,1,1,8,1,1,2,1,1,1
234,1 tablespoon cornstarch,1,1,3,1,1,2,0,1,1
237,1 cup sugar,1,1,3,1,1,2,0,1,1
238,2 tablespoons cornstarch,1,1,3,1,1,2,0,1,1
242,1 cups fat free sour cream,1,1,6,1,1,3,0,1,1
243,2 tablespoons sugar,1,1,3,1,1,2,0,1,1
248,1 cup fresh or frozen thawed wild blueberries,2,1,8,1,1,2,1,1,1
264,remaining 1 cup blueberry puree aside,2,1,6,1,1,2,1,1,1

In [77]:
def ner_label(data):
    lst=[]
    lst2=[]
    data2 = data.loc[data['label'] ==1 ]
    data2 = data2['Sentence']
    df = data2.to_string()
    nlp = spacy.load("output/model-best")
    doc = nlp(df)
    for ent in doc.ents:
        lst.append(ent.text)
        lst2.append(ent.label_)
        final = pd.DataFrame(list(zip(lst, lst2)),columns =['Name', 'val'])
    return final

In [78]:
ner_label(df)

                     Name         val
0           vanilla wafer  INGREDIENT
1                   sugar  INGREDIENT
2                  butter  INGREDIENT
3             blueberries  INGREDIENT
4            cornstarch\n  INGREDIENT
5                   sugar  INGREDIENT
6              cornstarch  INGREDIENT
7              sour cream  INGREDIENT
8                   sugar  INGREDIENT
9             blueberries  INGREDIENT
10  blueberry puree aside  INGREDIENT